name: photobucket-infra
runtime: dotnet
description: A Blazor static web app for guests from your wedding, birthday party or any event to submit photos.
config:
  pulumi:tags:
    value:
      pulumi:template: azure-csharp
